CREATE DATABASE DB_AUTOMOVEIS;
USE DB_AUTOMOVEIS;

CREATE TABLE  TBL_CLIENTE ( 
    COD_CLIENTE SMALLINT PRIMARY KEY AUTO_INCREMENT, 
    NOME VARCHAR(50) NOT NULL, 
    RG INT(9) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    TELEFONE INT(10),
    ENDERECO VARCHAR(150) NOT NULL
);  

CREATE TABLE TBL_AUTOMOVEL (
    PLACA VARCHAR(10) PRIMARY KEY, 
    COD_RENAVAN INT(11) NOT NULL,
    FABRICANTE VARCHAR(20) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    ANO INT(4) NOT NULL
);

CREATE TABLE TBL_OCORRENCIA (
    NUM_OCORRENCIA INT PRIMARY KEY, 
    DATA_OCORRENCIA DATE NOT NULL,
    LOCAL_OCO VARCHAR(60) NOT NULL,
    DESCRICAO VARCHAR(120) NOT NULL
);


 